start: _blank_line* (script | corrections) _blank_line*

script: command (_separator command)*
corrections: correction (_separator correction)*

?command: path_command
        | "rm"
        | inline_mutation
        | heredoc_mutation
        | inline_initializer
        | heredoc_initializer

path_command: PATH_OP SP PATH
inline_mutation: TYPE_OP SP target SP QUOTED
heredoc_mutation: TYPE_OP SP target SP "<<PATCH" NL _patch_body "PATCH"
inline_initializer: "type" SP QUOTED
heredoc_initializer: "type" SP "<<PATCH" NL _patch_body "PATCH"

?target: ROW
       | ROW ".." ROW
       | ROW SP TARGET_QUOTED (SP POSINT)?

?correction: replacement
           | acceptance
           | deletion
           | insertion_before
           | insertion_after

replacement: POSINT ":" SP? command
acceptance: POSINT ":" SP "accept"
deletion: "-" POSINT
insertion_before: "+" POSINT ":" SP? command
insertion_after: POSINT "+:" SP? command

_separator: NL _blank_line*
_blank_line: HSPACE? NL
_patch_body: (PATCH_BODY_LINE | NL)*

PATH_OP: "in" | "new" | "mv"
TYPE_OP: "type" | "type-" | "type+"
ROW: /[1-9][0-9]*:[0-9a-f]{4}/
POSINT: /[1-9][0-9]*/

SP: " "
HSPACE: /[ \t]+/
PATH: /[^\r\n]+/
NL: /\r?\n/
QUOTED: /"(?:\\(?:["\\\/bfnrt]|u[0-9A-Fa-f]{4})|[^\x00-\x1F"\\]|\t)*"/
TARGET_QUOTED: /"(?:\\(?:["\\\/t]|u(?:0009|00[2-9A-Fa-f][0-9A-Fa-f]|0[1-9A-Fa-f][0-9A-Fa-f]{2}|[1-9A-Fa-f][0-9A-Fa-f]{3}))|[^\x00-\x1F"\\]|\t)+"/
PATCH_BODY_LINE: /(?:PATCH[^\r\n]+|PATC[^H\r\n][^\r\n]*|PAT[^C\r\n][^\r\n]*|PA[^T\r\n][^\r\n]*|P[^A\r\n][^\r\n]*|PATC|PAT|PA|P|[^P\r\n][^\r\n]*)(?:\r\n|\n)/
