start: _blank_line* script _blank_line*

script: command (_separator command)*

?command: path_command
        | "rm"
        | inline_mutation
        | heredoc_mutation
        | inline_initializer
        | heredoc_initializer

path_command: PATH_OP SP PATH
inline_mutation: "type" SP target SP QUOTED
               | "add" SP add_destination SP QUOTED
heredoc_mutation: "type" SP target SP HEREDOC_MARKER NL _patch_body "PATCH"
                | "add" SP add_destination SP HEREDOC_MARKER NL _patch_body "PATCH"
inline_initializer: "type" SP QUOTED
heredoc_initializer: "type" SP HEREDOC_MARKER NL _patch_body "PATCH"

HEREDOC_MARKER: "<<PATCH" | "<<PATCH-"

?target: ROW
       | ROW ".." ROW
       | ROW SP TARGET_QUOTED (SP POSINT)?
       | TARGET_QUOTED (SP POSINT)?

?add_destination: ROW
                | ROW SP TARGET_QUOTED (SP POSINT)?
                | TARGET_QUOTED (SP POSINT)?
                | "EOF"


_separator: NL _blank_line*
_blank_line: HSPACE? NL
_patch_body: (PATCH_BODY_LINE | NL)*

PATH_OP: "in" | "new" | "mv"
ROW: /[1-9][0-9]*:[0-9a-f]{4}/
POSINT: /[1-9][0-9]*/

SP: " "
HSPACE: /[ \t]+/
PATH: /[^\r\n]+/
NL: /\r?\n/
QUOTED: /"(?:\\(?:["\\\/bfnrt]|u[0-9A-Fa-f]{4})|[^\x00-\x1F"\\]|\t)*"/
TARGET_QUOTED: /"(?:\\(?:["\\\/nt]|u(?:000[9Aa]|00[2-9A-Fa-f][0-9A-Fa-f]|0[1-9A-Fa-f][0-9A-Fa-f]{2}|[1-9A-Fa-f][0-9A-Fa-f]{3}))|[^\x00-\x1F"\\]|\t)+"/
PATCH_BODY_LINE: /(?:(?:PATCH[^\r\n]+|PATC[^H\r\n][^\r\n]*|PAT[^C\r\n][^\r\n]*|PA[^T\r\n][^\r\n]*|P[^A\r\n][^\r\n]*|PATC|PAT|PA|P|[^Pat\r\n][^\r\n]*)|(?:t|t[^y\r\n][^\r\n]*|ty|ty[^p\r\n][^\r\n]*|typ|typ[^e\r\n][^\r\n]*|type|type[^ \r\n][^\r\n]*|a|a[^d\r\n][^\r\n]*|ad|ad[^d\r\n][^\r\n]*|add|add[^ \r\n][^\r\n]*)|(?:type|add) (?:[^\r\n]*[^H\-\r\n]|(?:[^\r\n]*[^H\r\n])?-|(?:[^\r\n]*[^C\r\n])?H-?|(?:[^\r\n]*[^T\r\n])?CH-?|(?:[^\r\n]*[^A\r\n])?TCH-?|(?:[^\r\n]*[^P\r\n])?ATCH-?|(?:[^\r\n]*[^<\r\n])?PATCH-?|(?:[^\r\n]*[^<\r\n])?<PATCH-?|[^\r\n]*[^ \r\n]<<PATCH-?)?)(?:\r\n|\n)/
