start: _blank_line* recovery (_separator recovery)* _blank_line*

?recovery: HANDLE SP "drop"
         | HANDLE SP "target" SP target
         | HANDLE SP "operation" SP TYPE_OP
         | HANDLE SP "value" SP value
         | HANDLE SP VHANDLE SP VALUE_OP SP value
         | HANDLE SP STRUCTURAL_OP SP command

?command: path_command
        | "rm"
        | inline_mutation
        | heredoc_mutation
        | inline_initializer
        | heredoc_initializer

path_command: PATH_OP SP PATH
inline_mutation: TYPE_OP SP target SP QUOTED
heredoc_mutation: TYPE_OP SP target SP "<<PATCH" NL _patch_body "PATCH"
inline_initializer: "type" SP QUOTED
heredoc_initializer: "type" SP "<<PATCH" NL _patch_body "PATCH"

?target: ROW
       | ROW ".." ROW
       | ROW SP TARGET_QUOTED (SP POSINT)?
       | TARGET_QUOTED (SP POSINT)?

?value: QUOTED
      | "<<PATCH" NL _patch_body "PATCH"

_separator: NL _blank_line*
_blank_line: HSPACE? NL
_patch_body: (PATCH_BODY_LINE | NL)*

PATH_OP: "in" | "new" | "mv"
TYPE_OP: "type" | "type-" | "type+"
VALUE_OP: "value" | "value-" | "value+"
STRUCTURAL_OP: "replace" | "before" | "after"
HANDLE: /C[1-9][0-9]*:[0-9a-f]{4}/
VHANDLE: /V[1-9][0-9]*:[0-9a-f]{4}/
ROW: /[1-9][0-9]*:[0-9a-f]{4}/
POSINT: /[1-9][0-9]*/

SP: " "
HSPACE: /[ \t]+/
PATH: /[^\r\n]+/
NL: /\r?\n/
QUOTED: /"(?:\\(?:["\\\/bfnrt]|u[0-9A-Fa-f]{4})|[^\x00-\x1F"\\]|\t)*"/
TARGET_QUOTED: /"(?:\\(?:["\\\/nt]|u(?:000[9Aa]|00[2-9A-Fa-f][0-9A-Fa-f]|0[1-9A-Fa-f][0-9A-Fa-f]{2}|[1-9A-Fa-f][0-9A-Fa-f]{3}))|[^\x00-\x1F"\\]|\t)+"/
PATCH_BODY_LINE: /(?:(?:PATCH[^\r\n]+|PATC[^H\r\n][^\r\n]*|PAT[^C\r\n][^\r\n]*|PA[^T\r\n][^\r\n]*|P[^A\r\n][^\r\n]*|PATC|PAT|PA|P|[^Pt\r\n][^\r\n]*)|(?:t|t[^y\r\n][^\r\n]*|ty|ty[^p\r\n][^\r\n]*|typ|typ[^e\r\n][^\r\n]*|type|type[^ +\r\n-][^\r\n]*|type[+-]|type[+-][^ \r\n][^\r\n]*)|type(?:[+-])? (?:[^\r\n]{0,6}|[^<\r\n][^\r\n]{6}|<[^<\r\n][^\r\n]{5}|<<[^P\r\n][^\r\n]{4}|<<P[^A\r\n][^\r\n]{3}|<<PA[^T\r\n][^\r\n]{2}|<<PAT[^C\r\n][^\r\n]|<<PATC[^H\r\n]|[^\r\n]*[^ \r\n][^\r\n]{7}|[^\r\n]* [^<\r\n][^\r\n]{6}|[^\r\n]* <[^<\r\n][^\r\n]{5}|[^\r\n]* <<[^P\r\n][^\r\n]{4}|[^\r\n]* <<P[^A\r\n][^\r\n]{3}|[^\r\n]* <<PA[^T\r\n][^\r\n]{2}|[^\r\n]* <<PAT[^C\r\n][^\r\n]|[^\r\n]* <<PATC[^H\r\n]))(?:\r\n|\n)/
