start: _blank_line* recovery (_separator recovery)* _blank_line*

recovery: HANDLE SP target

?target: ROW
       | ROW ".." ROW
       | ROW SP TARGET_QUOTED (SP POSINT)?
       | TARGET_QUOTED (SP POSINT)?

_separator: NL _blank_line*
_blank_line: HSPACE? NL

HANDLE: /C[1-9][0-9]*:[0-9a-f]{4}/
ROW: /[1-9][0-9]*:[0-9a-f]{4}/
POSINT: /[1-9][0-9]*/

SP: " "
HSPACE: /[ \t]+/
NL: /\r?\n/
TARGET_QUOTED: /"(?:\\(?:["\\\/nt]|u(?:000[9Aa]|00[2-9A-Fa-f][0-9A-Fa-f]|0[1-9A-Fa-f][0-9A-Fa-f]{2}|[1-9A-Fa-f][0-9A-Fa-f]{3}))|[^\x00-\x1F"\\]|\t)+"/
